### ISSUE TITLE
Invalid argument(s): Cannot create a Trace from null

### ISSUE THREAD

**Issue by yy1300326388** [kiwi-bop/flutter_crashlytics#13]
```java
Invalid argument(s): Cannot create a Trace from null.
#0      new Trace.from (package:stack_trace/src/trace.dart:105:7)
#1      FlutterCrashlytics._cause (package:flutter_crashlytics/flutter_crashlytics.dart:75:12)
#2      FlutterCrashlytics.reportCrash (package:flutter_crashlytics/flutter_crashlytics.dart:37:16)
<asynchronous suspension>
#3      main.<anonymous closure> (package:student_app/main.dart:59:10)
<asynchronous suspension>
#4      _rootRunBinary (dart:async/zone.dart:1148:13)
#5      _RootZone.runBinary (dart:async/zone.dart:1385:12)
#6      runZoned.<anonymous closure> (dart:async/zone.dart:1479:21)
#7      _CustomZone.handleUncaughtError (dart:async/zone.dart:1003:19)
#8      _nullErrorHandler (dart:async/stream_impl.dart:572:16)
#9      _rootRunBinary (dart:async/zone.dart:1144:38)
#10     _CustomZone.runBinary (dart:async/zone.dart:1037:19)
#11     _CustomZone.runBinaryGuarded (dart:async/zone.dart:939:7)
#12     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:355:15)
#13     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:373:16)
#14     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:272:7)
#15     _SyncStreamController._sendError (dart:async/stream_controller.dart:767:19)
#16     _StreamController._addError (dart:async/stream_controller.dart:647:7)
#17     _StreamController.addError (dart:async/stream_controller.dart:599:5)
#18     _AsyncDirectoryLister.error (dart:io/directory_impl.dart:442:18)
#19     _AsyncDirectoryLister.next.<anonymous closure> (dart:io/directory_impl.dart:391:15)
#20     _rootRunUnary (dart:async/zone.dart:1132:38)
#21     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#22     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#24     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#25     Future._completeWithValue (dart:async/future_impl.dart:486:5)
#26     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#27     _rootRun (dart:async/zone.dart:1124:13)
#28     _CustomZone.run (dart:async/zone.dart:1021:19)
#29     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#30     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#31     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#32     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```

**Comment by jaumard** [comment]
Are you able to reproduce this and share a small piece of code please ?

**Comment by yy1300326388** [comment]
@jaggernod  I will try it later

**Comment by jaumard** [comment]
@jaggernod can you take a look at this please ?
