### ISSUE TITLE
Exception when pass StackTrace - kotlin.TypeCastException: null cannot be cast to non-null type kotlin.Int

### ISSUE THREAD

**Issue by haart28** [kiwi-bop/flutter_crashlytics#16]
Hello, I use flutter_crashlytics 0.0.6 in my project. I also use Firebase Auth for flutter.
When I do user registration with Email which is already in use I got exception. This is expected behaviour and I handle it in "catchError" block like this:

```
.catchError((error, stackTrace) {
   FlutterCrashlytics().reportCrash(error, stackTrace, forceCrash: false);
}
```

But I see crash inside FlutterCrashlytics and I don't see my non-fatal in Fabric account. My logs are:

```
E/MethodChannel#flutter_crashlytics( 7262): Failed to handle method call
E/MethodChannel#flutter_crashlytics( 7262): kotlin.TypeCastException: null cannot be cast to non-null type kotlin.Int
E/MethodChannel#flutter_crashlytics( 7262): 	at com.kiwi.fluttercrashlytics.Utils.stackTraceElement(Utils.kt:21)
E/MethodChannel#flutter_crashlytics( 7262): 	at com.kiwi.fluttercrashlytics.Utils.create(Utils.kt:11)
E/MethodChannel#flutter_crashlytics( 7262): 	at com.kiwi.fluttercrashlytics.FlutterCrashlyticsPlugin.onMethodCall(FlutterCrashlyticsPlugin.kt:69)
E/MethodChannel#flutter_crashlytics( 7262): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/MethodChannel#flutter_crashlytics( 7262): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#flutter_crashlytics( 7262): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_crashlytics( 7262): 	at android.os.MessageQueue.next(MessageQueue.java:331)
E/MethodChannel#flutter_crashlytics( 7262): 	at android.os.Looper.loop(Looper.java:219)
E/MethodChannel#flutter_crashlytics( 7262): 	at android.app.ActivityThread.main(ActivityThread.java:6274)
E/MethodChannel#flutter_crashlytics( 7262): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_crashlytics( 7262): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
E/MethodChannel#flutter_crashlytics( 7262): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
E/flutter ( 7262): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter ( 7262): PlatformException(error, null cannot be cast to non-null type kotlin.Int, null)
E/flutter ( 7262): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
E/flutter ( 7262): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279:18)
E/flutter ( 7262): <asynchronous suspension>
E/flutter ( 7262): #2      FlutterCrashlytics.reportCrash (package:flutter_crashlytics/flutter_crashlytics.dart:42:27)
E/flutter ( 7262): <asynchronous suspension>
E/flutter ( 7262): #3      AuthPresenterImpl._onCatchError (package:app/ui/auth/auth_presenter.dart:109:26)
```

**Comment by jaumard** [comment]
@jaggernod so from what I understand here there no line number right ?
