### ISSUE TITLE
fastlane crashlytics step: halted compilation - can't extract Crashlytics build info from APK

### ISSUE THREAD

**Issue by zanuka** [kiwi-bop/flutter_crashlytics#80]
I've seen this reported in multiple places, however cannot seem to find any info regarding a fix. 

The full error when trying to run an fastlane flutter build using `com.crashlytics.sdk.android:crashlytics:2.9.9@aar` is 

``` bash
+------+-----------------------------+-------------+
|                 fastlane summary                 |
+------+-----------------------------+-------------+
| Step | Action                      | Time (in s) |
+------+-----------------------------+-------------+
| 1    | update_fastlane             | 7           |
| 2    | default_platform            | 0           |
| 3    | gradle                      | 4           |
| 4    | flutter build apk           | 75          |
|      | --target\=lib/config/produ  |             |
|      | ction.dart --rele           |             |
| 5    | read_pubspec_version        | 0           |
| 6    | read_changelog              | 0           |
| 💥   | crashlytics                 | 0           |
+------+-----------------------------+-------------+

[14:42:58]: fastlane finished with errors

[!]  WARN - Crashlytics halted compilation because it can't extract Crashlytics build info from the APK: /Users//xxx/xx/xx/build/app/outputs/apk/release/app-release.apk
Exception in thread "main" com.crashlytics.tools.android.exception.PluginException: Distribution upload failed.
        at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:667)
        at com.crashlytics.tools.android.DeveloperTools.processArgsInternal(DeveloperTools.java:348)
        at com.crashlytics.tools.android.DeveloperTools.main(DeveloperTools.java:273)
Caused by: com.crashlytics.tools.android.exception.DistributionException: Crashlytics halted compilation because it can't extract Crashlytics build info from the APK: /Users/xxx/xx/xxx/build/app/outputs/apk/release/app-release.apk
        at com.crashlytics.tools.android.DistributionTasks.uploadDistribution(DistributionTasks.java:64)
        at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:665)
        ... 2 more
```

have followed the exact installation configurations and examples from this repo, but to no avail. it used to work fine. 

this happened after we upgraded flutter project for AndroidX doing the following in dependencies

``` gradle
compile('com.crashlytics.sdk.android:crashlytics:2.9.9@aar') {
        transitive = true;
    }
```

**Comment by jaumard** [comment]
Hey @zanuka, can you test with v 1.0.0 please and let me know :)

**Comment by zanuka** [comment]
Yes will do soon, just in the middle of some other tasks.

**Comment by zanuka** [comment]
Still getting the same error using `^1.0.0`

**Comment by jaumard** [comment]
No problem on my side, I just upgrade my project to 1.0.0 and my delivery to crashlytics beta has worked. 
But you shouldn't have crashlytics on your dependency as it's bundle with the plugin already that might be your issue

**Comment by zanuka** [comment]
interesting. I pulled out the dependency in build.gradle as recommended with 1.0.0 plugin, however I still get the same result when running my fastlane android beta channel 

```
| 6    | read_changelog                        | 0           |
| 💥   | crashlytics                           | 0           |
+------+---------------------------------------+-------------+

[11:29:19]: fastlane finished with errors

[!]  WARN - Crashlytics halted compilation because it can't extract Crashlytics build info from the APK: /Users/zanuka/workspace/tierratech/logmate_flutter/build/app/outputs/apk/release/app-release.apk
```
not sure what else could be causing conflicts

**Comment by zanuka** [comment]
looks like it might be related to `crashlytics-build.properties` as noted [here](https://github.com/jenkinsci/fabric-beta-publisher-plugin/issues/24)

**Comment by zanuka** [comment]
@jaumard what version of Android Gradle Plugin are you using?

**Comment by jaumard** [comment]
https://github.com/kiwi-bop/flutter_crashlytics/blob/master/android/build.gradle#L11
https://github.com/kiwi-bop/flutter_crashlytics/blob/master/android/build.gradle#L37 :)

**Comment by zanuka** [comment]
@jaumard Yeah I've compared my config against your files but something else seems to be happening with our additional configs possibly conflicting. Getting the same error. 

Perhaps you could have a look at my app build.gradle and see if you spot anything that could cause conflicts. 

```gradle
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    throw new GradleException("versionCode not found. Define flutter.versionCode in the local.properties file.")
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    throw new GradleException("versionName not found. Define flutter.versionName in the local.properties file.")
}

def keystorePropertiesFile = rootProject.file("key.properties")
def keystoreProperties = new Properties()
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

apply plugin: 'com.android.application'
apply plugin: 'io.fabric'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    
    compileSdkVersion 28    

    defaultConfig {        
        applicationId "XXXXX"
        minSdkVersion 23
        targetSdkVersion 28        
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"        

    }

    lintOptions {
        disable 'InvalidPackage'
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release         

            ndk {
                abiFilters 'armeabi', 'x86', 'armeabi-v7a', 'x86_64' //, "arm64-v8a" - do not include as breaks launch | GM 5 Apr 2019
            }          
        }
    }
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
    implementation 'io.intercom.android:intercom-sdk-base:5.2.1'
    api('com.crashlytics.sdk.android:crashlytics:2.9.9@aar') {
        transitive = true
    }
    api('com.crashlytics.sdk.android:crashlytics-ndk:2.0.5@aar') {
        transitive = true
    }
}

flutter {
    source '../..'
}

```

**Comment by zanuka** [comment]
thinking it could have something to do with the ndk config

**Comment by vnagendra** [comment]
Fought the same problem for a few hours. I have two projects one of which was doing just fine and the other was having this issue. Went through `app/build.gradle` line by line trying to figure out what is going on. Here are some steps for posterity

1. Check to see if `crashlytics-build.properties` is present in the APK. You'll need an APK viewer (such as the one bundled with Android Studio). 
 - This file can be found in the `assets` folder (inside the APK)
 - This file is also _generated_ as an intermediate, which maybe easier to find like so. Execute this find from the project directory (where you can find `pubspec.yaml` file. 
```
➜  project git:(master) ✗ find build -name crashlytics-build.properties
build/app/intermediates/merged_assets/release/out/crashlytics-build.properties
```
 - Goes without saying, if this isn't found, it isn't going to work 😀

2. For some strange reason, version `  flutter_crashlytics: ^ 0.2.1+1` and `  flutter_crashlytics: ^1.0.0` both have a dependency on kotlin plugin. 
 - My project with 0.2.1 happened to be kotlin, because of which I missed this
 - So adding `apply plugin: 'kotlin-android'` in the `app/build.gradle` magically made this file appear! 

I'd be very curious to hear _why_ that is the case, because the example project doesn't seem to have this dependency at all. I wonder why the example project is working (or why my project wasn't working).

**Comment by zanuka** [comment]
Thanks for posting this info @vnagendra ... in the process of trying to fix based on your findings ⚡️

**Comment by zanuka** [comment]
@vnagendra do you have the following in your android build.gradle dependencies?
`classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.31'`

**Comment by zanuka** [comment]
adding the `apply plugin: 'kotlin-android'` to `app/build.gradle` did the trick, but only with the following in the android `build.gradle`:

```
buildscript {
    repositories {
        google()
        jcenter()
        maven { url 'https://maven.fabric.io/public' }
        maven { url 'https://plugins.gradle.org/m2/' }
    }

    dependencies {
        classpath 'io.fabric.tools:gradle:1.+'
        classpath 'com.android.tools.build:gradle:3.3.2'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.31'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}
```
